
baseURL             = "https://hydrotherapie-eaux-vives.ch"
languageCode        = "fr-FR"
title               = "Cabinet Carolina Erni — Hydrothérapie & massages"
canonifyurls        = true
disableRSS          = true
ignoreFiles         = ["static/_stock", ".DS_Store"]

[params]
  otherURL          = "https://hydrotherapie-eaux-vives.ch"
  description       = "Cabinet d’hydrothérapie et de massages aux Eaux-Vives à Genève"
  author            = "Carolina Erni"
  prodURL           = "https://hydrotherapie-eaux-vives.ch"

[outputs]
  home = ["HTML", "Robots"]
  page = []
  taxonomy = []

[outputFormats]
  [outputFormats.Robots]
    mediaType = "text/plain"
    baseName = "robots"
    isPlainText = true
    notAlternative = true

# [permalinks]
#   post = "/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
